const events = [
	{
		imgage: "",
		id: 1,
		title: "Community Prayer Gathering",
		date: "2024-03-20",
		location: "St. Peter's Church, NY",
		description: "Join us for a peaceful evening of prayer and reflection.",
		category: "Religious",
	},
	{
		imgage: "",
		id: 2,
		title: "Food Donation Drive",
		date: "2024-03-25",
		location: "Central Park, NY",
		description: "Help distribute food to the homeless and those in need.",
		category: "Charity",
	},
	{
		imgage: "",
		id: 3,
		title: "Neighborhood Cleanup",
		date: "2024-03-30",
		location: "Brooklyn Community Center, NY",
		description: "Join hands to clean up and beautify our neighborhood.",
		category: "Social",
	},
	{
		imgage: "",
		id: 4,
		title: "Easter Sunday Mass",
		date: "2024-03-31",
		location: "Holy Trinity Church, LA",
		description: "Celebrate Easter with a special mass service.",
		category: "Religious",
	},
	{
		imgage: "",
		id: 5,
		title: "Blood Donation Camp",
		date: "2024-04-05",
		location: "Red Cross Center, Chicago",
		description: "Donate blood and help save lives.",
		category: "Charity",
	},
	{
		imgage: "",
		id: 6,
		title: "Fundraising Gala for Orphans",
		date: "2024-04-10",
		location: "Hilton Grand, NY",
		description:
			"An evening of entertainment and charity fundraising for orphanages.",
		category: "Charity",
	},
	{
		imgage: "",
		id: 7,
		title: "Annual Cultural Festival",
		date: "2024-04-15",
		location: "Downtown Hall, San Francisco",
		description:
			"A celebration of diverse cultures with music, dance, and food.",
		category: "Social",
	},
	{
		imgage: "",
		id: 8,
		title: "Christmas Carol Night",
		date: "2024-12-24",
		location: "Greenwood Park, Seattle",
		description: "Enjoy a night of Christmas carols and festive spirit.",
		category: "Religious",
	},
];

export default events;
